from __future__ import annotations

from typing import Optional, TYPE_CHECKING

import math

import jax
import jax.numpy as jnp
import equinox as eqx
from jaxtyping import Array, Scalar, ScalarLike, PRNGKeyArray

from .._introspect import CountDict, Path
from ..hilbert_space import AbstractHilbertSpace, AbstractState
from .base import AbstractExponentiator, NotExponentiableError, Order
from ..eig import op_spectral_bounds_lanczos

if TYPE_CHECKING:
    from ..operator import Operator



# TODO:
#   Alternative adapation schemes evaluating t over range [t0, t1] for timestepping and exponential integrators



# Backward-error parameters for the scaling-and-squaring Taylor scheme of Al-Mohy &
# Higham (2011), Table 3.1. THETA_TABLES[tol][m - 1] is the largest ||h (A - mu I)||
# for which the degree-m truncated Taylor polynomial has backward error <= tol.
#
# A ladder of tolerances rather than just the two unit roundoffs: theta_m grows as
# the target loosens, so a looser target needs fewer Taylor terms and fewer
# squarings for the same operator. 2**-53 and 2**-24 are the float64 and float32
# unit roundoffs, the natural defaults.
#
# Generated by utils/mohy_backward_error.py; regenerate rather than hand-edit.
M_MAX = 55
P_MAX = 8
NUM_BLOCK_SAMPLES = 2
NUM_BLOCK_ITERATIONS = 3

THETA_TABLES = {
    2.0**-53: jnp.array([
        2.220446e-16, 2.5809568e-8, 1.3863479e-5, 0.00033971688, 0.0024008764,
        0.0090656564, 0.023844555, 0.049912289, 0.089577602, 0.14418298,
        0.21423581, 0.29961589, 0.39977753, 0.51391469, 0.64108352,
        0.78028743, 0.93053285, 1.0908637, 1.2603811, 1.4382526,
        1.623716, 1.8160778, 2.0147108, 2.2190489, 2.4285825,
        2.6428535, 2.8614496, 3.0840005, 3.3101728, 3.5396663,
        3.7722105, 4.0075611, 4.2454974, 4.4858199, 4.7283473,
        4.9729156, 5.2193754, 5.4675906, 5.7174374, 5.9688026,
        6.2215827, 6.4756827, 6.7310159, 6.9875023, 7.2450684,
        7.5036467, 7.7631747, 8.0235947, 8.2848536, 8.546902,
        8.8096943, 9.0731879, 9.3373435, 9.6021245, 9.8674967,
    ]),
    1e-14: jnp.array([
        2.0e-14, 2.4494895e-7, 6.214362e-5, 0.001046407, 0.0059023783,
        0.019165688, 0.045231028, 0.087238141, 0.14684582, 0.22447743,
        0.31969303, 0.43152581, 0.5587345, 0.69997391, 0.85390127,
        1.0192375, 1.1947985, 1.3795081, 1.5723996, 1.7726111,
        1.9793778, 2.1920229, 2.4099482, 2.6326252, 2.8595864,
        3.0904185, 3.324755, 3.5622708, 3.8026769, 4.0457158,
        4.2911577, 4.5387971, 4.7884498, 5.0399506, 5.2931505,
        5.5479156, 5.8041246, 6.0616679, 6.3204462, 6.580369,
        6.8413543, 7.103327, 7.3662189, 7.6299674, 7.8945151,
        8.1598095, 8.4258023, 8.692449, 8.9597087, 9.2275436,
        9.4959188, 9.764802, 10.034163, 10.303975, 10.574211,
    ]),
    1e-12: jnp.array([
        2.0e-12, 2.4494875e-6, 0.00028842773, 0.003307471, 0.014803494,
        0.041158944, 0.08686662, 0.15397221, 0.24259255, 0.35164222,
        0.47942167, 0.6240065, 0.78347522, 0.95602796, 1.1400385,
        1.3340687, 1.5368622, 1.7473303, 1.9645322, 2.1876569,
        2.416005, 2.6489724, 2.8860371, 3.1267464, 3.3707069,
        3.6175759, 3.8670541, 4.118879, 4.3728201, 4.6286742,
        4.8862617, 5.1454235, 5.4060182, 5.6679198, 5.9310159,
        6.1952058, 6.460399, 6.7265143, 6.9934785, 7.2612255,
        7.5296952, 7.7988334, 8.0685908, 8.3389225, 8.6097874,
        8.8811483, 9.1529708, 9.4252236, 9.6978779, 9.9709073,
        10.244287, 10.517996, 10.792012, 11.066316, 11.340892,
    ]),
    1e-10: jnp.array([
        2.0e-10, 2.4494672e-5, 0.0013383881, 0.010443601, 0.037043133,
        0.088069163, 0.1660333, 0.27024079, 0.3983375, 0.54737742,
        0.71440562, 0.89672428, 1.0919839, 1.2981888, 1.5136659,
        1.7370205, 1.9670928, 2.2029172, 2.443688, 2.6887309,
        2.9374794, 3.1894555, 3.444254, 3.7015302, 3.9609895,
        4.2223791, 4.485481, 4.7501068, 5.0160927, 5.283296,
        5.5515918, 5.8208708, 6.0910363, 6.3620033, 6.6336964,
        6.9060485, 7.179, 7.4524977, 7.7264939, 8.0009459,
        8.2758151, 8.5510671, 8.8266704, 9.102597, 9.378821,
        9.6553193, 9.9320707, 10.209056, 10.486257, 10.763659,
        11.041246, 11.319005, 11.596923, 11.87499, 12.153194,
    ]),
    1e-8: jnp.array([
        2.0e-8, 0.00024492648, 0.0062041909, 0.032871536, 0.09217192,
        0.18701593, 0.31455546, 0.46985733, 0.64786588, 0.84415377,
        1.0550902, 1.277783, 1.5099544, 1.7498155, 1.9959578,
        2.2472669, 2.5028553, 2.7620119, 3.024162, 3.2888387,
        3.5556595, 3.8243092, 4.0945262, 4.3660925, 4.6388248,
        4.9125688, 5.1871935, 5.4625873, 5.7386546, 6.0153135,
        6.2924932, 6.5701324, 6.8481777, 7.1265827, 7.4053069,
        7.6843146, 7.9635744, 8.2430587, 8.522743, 8.8026058,
        9.0826277, 9.3627916, 9.6430823, 9.9234862, 10.203991,
        10.484586, 10.765261, 11.046007, 11.326816, 11.607682,
        11.888597, 12.169557, 12.450555, 12.731586, 13.012647,
    ]),
    2.0**-24: jnp.array([
        1.1920928e-7, 0.00059788589, 0.011233865, 0.051166194, 0.13084872,
        0.24952893, 0.40145824, 0.58005246, 0.77951134, 0.99518408,
        1.2234795, 1.4616615, 1.7076485, 1.9598506, 2.2170444,
        2.4782809, 2.7428171, 3.0100664, 3.2795612, 3.5509262,
        3.8238574, 4.098107, 4.3734713, 4.6497822, 4.9268998,
        5.2047072, 5.4831061, 5.7620134, 6.0413588, 6.3210821,
        6.6011322, 6.8814648, 7.1620422, 7.4428313, 7.7238038,
        8.004935, 8.2862033, 8.5675898, 8.8490782, 9.1306539,
        9.4123042, 9.694018, 9.9757853, 10.257597, 10.539447,
        10.821326, 11.10323, 11.385153, 11.66709, 11.949037,
        12.23099, 12.512945, 12.794901, 13.076854, 13.358801,
    ]),
    1e-6: jnp.array([
        1.9999973e-6, 0.0024472427, 0.028625538, 0.10245061, 0.22624993,
        0.39105554, 0.58659231, 0.80449864, 1.0386311, 1.2846184,
        1.5393652, 1.8006649, 2.0669268, 2.3369885, 2.6099898,
        2.8852852, 3.1623849, 3.4409127, 3.7205769, 4.0011488,
        4.282448, 4.5643307, 4.8466819, 5.1294084, 5.4124348,
        5.6956996, 5.9791523, 6.2627514, 6.5464626, 6.8302575,
        7.1141126, 7.3980082, 7.681928, 7.9658583, 8.2497878,
        8.5337069, 8.8176077, 9.1014837, 9.3853292, 9.6691399,
        9.952912, 10.236642, 10.520328, 10.803968, 11.087561,
        11.371104, 11.654597, 11.93804, 12.221432, 12.504772,
        12.788061, 13.071299, 13.354486, 13.637621, 13.920706,
    ]),
    1e-4: jnp.array([
        0.00019997334, 0.024272829, 0.12933773, 0.31019046, 0.53849941,
        0.79404743, 1.0651857, 1.3454084, 1.6309927, 1.9197662,
        2.2104085, 2.5021096, 2.7943542, 3.086816, 3.3792826,
        3.6716187, 3.9637368, 4.2555831, 4.5471249, 4.8383448,
        5.1292351, 5.4197951, 5.7100284, 5.9999419, 6.2895441,
        6.578845, 6.8678551, 7.1565852, 7.4450462, 7.7332488,
        8.0212037, 8.3089208, 8.5964102, 8.883681, 9.1707425,
        9.4576031, 9.7442711, 10.030754, 10.31706, 10.603195,
        10.889166, 11.17498, 11.460642, 11.746159, 12.031535,
        12.316776, 12.601887, 12.886872, 13.171736, 13.456482,
        13.741116, 14.025641, 14.310059, 14.594376, 14.878594,
    ]),
}


def hutchinson(
    operator: Operator,
    num_samples: int=10,
    key: PRNGKeyArray=jax.random.key(0)) -> Scalar:

    hilbert_space = operator.domain
    sign_coeffs = 1 - 2 * jax.random.bernoulli(key, shape=(num_samples, hilbert_space.dim))
    y = hilbert_space.from_coeffs(sign_coeffs)
    vals = hilbert_space.expected_value(operator, y)
    return jnp.average(vals)


def norm1(y: AbstractState) -> Scalar:
    """
    Computes 1-norm of y
    """
    return jnp.sum(jnp.abs(y.coeffs), axis=-1)


def normalize(Y: AbstractState) -> AbstractState:
    """
    Normalizes columns of batched state Y to have unit 1-norm.
    """
    M = Y.coeffs
    coeffs = M / jnp.where(jnp.abs(M) > 0, jnp.abs(M), jnp.ones_like(M))
    return Y.hilbert_space.from_coeffs(coeffs)


def _top_indices(h: Array, num_indices: int, exclude: Optional[Array]=None) -> Array:
    """
    Returns indices of top num_indices entries in h sorted in decreasing order, 
    excluding those indices in exclude. When num_indices is small compared to h.shape[0], 
    this is faster than argsort(h)[:num_indices] (O(num_indices * n) vs. O(n log n))
    """
    if exclude is not None:
        h = h.at[exclude].set(-jnp.inf)

    indices = []
    for _ in range(num_indices):
        idx = jnp.argmax(h)
        indices.append(idx)
        h = h.at[idx].set(-jnp.inf)

    return jnp.stack(indices)


def _unit_states(hilbert_space: AbstractHilbertSpace, indices: Array) -> AbstractState:
    """
    Returns e_i for i in indices
    """
    num_indices = indices.shape[0]
    coeffs = jnp.zeros((num_indices, hilbert_space.dim))
    return hilbert_space.from_coeffs(coeffs.at[jnp.arange(num_indices), indices].set(1.0))


def block_estimate(
    operator: Operator,
    p: int=1,
    num_samples: int=2,
    num_iterations: int=3,
    key: PRNGKeyArray=jax.random.key(0)) -> Scalar:

    """
    Simplification of the below referenced method to estimate the 1-norm of the matrix A^p, 
    skipping convergence / early termination checks. 

        Higham, Nicholas J., and Françoise Tisseur.
        "A block algorithm for matrix 1-norm estimation, with an application to 1-norm pseudospectra."
        SIAM Journal on Matrix Analysis and Applications 21.4 (2000): 1185-1201.
    """

    hilbert_space = operator.domain

    def action(_, y):
        return operator(y)

    def adj_action(_, y):
        return operator.adj_action(y)

    Y = hilbert_space.random(key, shape=(num_samples,))
    Y = hilbert_space.from_coeffs(Y.coeffs / norm1(Y)[:, None])

    Y = jax.lax.fori_loop(0, p, action, Y)
    est = jnp.max(norm1(Y))

    used = []
    for _ in range(num_iterations - 1):
        Z = jax.lax.fori_loop(0, p, adj_action, normalize(Y))
        h = jnp.max(jnp.abs(Z.coeffs), axis=0)

        indices = _top_indices(h, num_samples,
            exclude=jnp.concatenate(used) if used else None)
        used.append(indices)

        Y = jax.lax.fori_loop(0, p, action, _unit_states(hilbert_space, indices))
        est = jnp.maximum(est, jnp.max(norm1(Y)))

    return est


def _theta_table(max_tol: Optional[float]) -> Array:
    if max_tol is None:
        max_tol = 2.0**-53 if jax.config.x64_enabled else 2.0**-24

    admissible = [tol for tol in THETA_TABLES if tol <= max_tol]
    if not admissible:
        raise ValueError(
            f"max_tol={max_tol:g} is tighter than the tightest tabulated tolerance "
            f"{min(THETA_TABLES):g}. Regenerate with utils/mohy_backward_error.py "
            f"to go lower."
        )

    return THETA_TABLES[max(admissible)]


def _taylor_expm(
    op: Operator,
    h: ScalarLike,
    y: AbstractState,
    num_iterations: int) -> AbstractState:

    def taylor(carry, idx):
        exp_y, yk = carry
        yk_next = h * op.action(yk) / (idx + 1)
        exp_y_next = exp_y + yk_next
        return (exp_y_next, yk_next), None

    init = (y, y)
    idx_list = jnp.arange(num_iterations)
    (exp_y, _), _ = jax.lax.scan(taylor, init, idx_list)

    return exp_y


class TruncatedTaylorExponentiator(AbstractExponentiator):
    """
    Approximates exp(hA) @ y using a matrix-free adaption of the scaling + Taylor expansion
    method introduced by Mohy and Higham. For any μ and integer s,

        exp(hA) @ y = e^(hμ / s) * exp(h(A - μ * I) / s)^s @ y

    Let T_m be the truncated Taylor approximation of exp(X). Then the approximation is 
    computed by performing s steps of the iteration

        y_{k + 1} = e^(hμ / s) * T_m(h(A - μ * I) / s) @ y_{k}, y_0 = y

    Since the Taylor expansion has m terms, and is computed s times, the total amount 
    of computational effort required by this method can be approximated by s * m. The adapt 
    method identifies the m, s, and μ that minimizes s * m while ensuring that the backward
    error is at most max_tol. 

    References:

        1. Al-Mohy, Awad H., and Nicholas J. Higham. "Computing the action of the matrix
        exponential, with an application to exponential integrators."
        SIAM journal on scientific computing 33.2 (2011): 488-511.
    """
    m: int = eqx.field(static=True, default=55, converter=int)
    s: Optional[int] = eqx.field(static=True, default=None, converter=lambda s: s if s is None else int(s))
    mu: complex = eqx.field(static=True, default=0.0, converter=complex)
    max_tol: Optional[float] = eqx.field(static=True, default=None)

    def __check_init__(self):
        if self.m < 2 or self.m > M_MAX:
            raise ValueError(f"Recieved m={self.m} but m must be between 2 and {M_MAX}.")

    def adapt(self, op: Operator, dt_max: ScalarLike) -> AbstractExponentiator:

        # Essentially reproduces Code Fragment 3.1 in the above referenced Mohy and Higham paper

        from ..operator import NoRealSpectrumError

        dim = op.domain.dim

        try:
            lmin, lmax = op.spectral_bounds
            mu1 = 0.5 * (lmin + lmax)
            mu2 = 1.0 / dim * hutchinson(op)

            theta1 = block_estimate(
                jnp.abs(dt_max) * (op - mu1), 
                num_samples=NUM_BLOCK_SAMPLES, num_iterations=NUM_BLOCK_ITERATIONS)

            theta2 = block_estimate(
                jnp.abs(dt_max) * (op - mu2), 
                num_samples=NUM_BLOCK_SAMPLES, num_iterations=NUM_BLOCK_ITERATIONS)

            mu = mu1 if theta1 < theta2 else mu2
            theta = min(theta1, theta2)
        except (NotImplementedError, NoRealSpectrumError):
            mu = 1.0 / dim * hutchinson(op)
            theta = block_estimate(
                jnp.abs(dt_max) * (op - mu), 
                num_samples=NUM_BLOCK_SAMPLES, num_iterations=NUM_BLOCK_ITERATIONS)

        op_shift = op - mu
        theta_list = _theta_table(self.max_tol)
        m_list = jnp.arange(1, M_MAX + 1)

        if theta < 2 * NUM_BLOCK_SAMPLES * theta_list[-1] / M_MAX * P_MAX * (P_MAX + 3):
            s_list = jnp.maximum(1, jnp.ceil(theta / theta_list))
            idx = jnp.argmin(m_list * s_list)
            m = max(2, int(idx) + 1)
            s = jnp.maximum(1, math.ceil(theta / theta_list[m - 1]))
        else:
            # d_p = ||A^p||^(1/p) for p = 2 .. P_MAX + 1;  alpha_p = max(d_p, d_{p+1})
            ds = jnp.array([
                block_estimate(
                    jnp.abs(dt_max) * op_shift, 
                    num_samples=NUM_BLOCK_SAMPLES, num_iterations=NUM_BLOCK_ITERATIONS, p=p) ** (1.0 / p)
                for p in range(2, P_MAX + 2)
            ])
            alphas = jnp.maximum(ds[:-1], ds[1:])        # alphas[p - 2] = alpha_p,  p = 2..P_MAX
            p_list = jnp.arange(2, P_MAX + 1)

            # ceils[i, j] = ceil(alpha_{p_i} / theta_{m_j}) with m_j = j + 1
            ceils = jnp.ceil(alphas[:, None] / theta_list[None, :])
            cost = m_list[None, :] * ceils

            # admissible iff p(p - 1) - 1 <= m <= m_max, and m >= 2 for __check_init__
            admissible = (
                (p_list[:, None] * (p_list[:, None] - 1) - 1 <= m_list[None, :])
                & (m_list[None, :] >= 2)
            )
            cost = jnp.where(admissible, cost, jnp.inf)

            i, j = jnp.unravel_index(jnp.argmin(cost), cost.shape)
            m = int(m_list[j])
            s = max(1, int(ceils[i, j]))

        return TruncatedTaylorExponentiator(m, s, mu, self.max_tol)

    def exp(self, op: Operator, h: ScalarLike, y: AbstractState) -> AbstractState:
        theta_list = _theta_table(self.max_tol)
        
        if self.s is None:
            theta = block_estimate(
                jnp.abs(h) * (op - self.mu), 
                num_samples=NUM_BLOCK_SAMPLES, num_iterations=NUM_BLOCK_ITERATIONS)
                
            s = jnp.maximum(1, jnp.ceil(theta / theta_list[self.m - 1])).astype(int)
        else:
            s = self.s 

        op_shift = (op - self.mu) / s

        def loop(_, exp_y):
            step = jnp.exp(h * self.mu / s) * _taylor_expm(op_shift, h, exp_y, self.m)
            return step

        exp_y = jax.lax.fori_loop(0, s, loop, init_val=y)
        return exp_y

    @property
    def order(self) -> Order:
        return None

    def count(
        self, 
        op: Operator, 
        h: ScalarLike, 
        parent_path: Path=Path(), 
        field: str="") -> CountDict:
        
        i_count = op.interface_count(parent_path, field)

        if self.s is None:
            theta_list = _theta_table(self.max_tol)

            theta = block_estimate(
                jnp.abs(h) * (op - self.mu), 
                num_samples=NUM_BLOCK_SAMPLES, num_iterations=NUM_BLOCK_ITERATIONS)

            s = int(jnp.maximum(1, jnp.ceil(theta / theta_list[self.m - 1])))
            c_action = (s * self.m + NUM_BLOCK_ITERATIONS * NUM_BLOCK_SAMPLES) * i_count.action
            c_adj = ((NUM_BLOCK_ITERATIONS - 1) * NUM_BLOCK_SAMPLES) * i_count.adj_action
            return c_action + c_adj

        return self.s * self.m * i_count.action
