theme:
  name: material
  features:
      - navigation.sections
      - toc.integrate
      - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
          icon: material/weather-night
          name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
  icon:
    logo: material/sine-wave
  favicon: assets/sine-wave.svg

site_name: qmax
site_author: Ahmed Allibhoy
site_url: https://docs.qmax.io

repo_url: https://github.com/ahmedallibhoy/qmax
repo_name: ahmedallibhoy/qmax

hooks:
  - utils/mkdocs_hooks.py

exclude_docs: |
  _templates/

plugins:
  - search
  #- hippogriffe
  #- ipynb
  - mkdocstrings:
      custom_templates: docs/_templates
      handlers:
        python:
          options:
            force_inspection: true
            heading_level: 4
            inherited_members: true
            members_order: source
            show_bases: false
            show_if_no_docstring: false
            show_overloads: true
            show_root_heading: true
            #show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_section_style: list

  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences  # needed for syntax highlighting
  - pymdownx.details
  - pymdownx.snippets:  # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤"  # Adds a clickable permalink to each section heading
      toc_depth: 4  # Prevents h5, h6 (i.e. methods) from showing up in the TOC.

extra_css:
    - _static/custom.css

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - 'index.md'
  - Tutorial: tutorial.md
  #- Philosophy of qmax: approach.md
  - About the Author: about.md
  - Examples:
    - Quantum Harmonic Oscillator: 'examples/harmonic_oscillator.md'
    #- Hydrogen Atom: 'examples/hydrogen.md'
    - Driven Two Level System: 'examples/controlled_two_level.md'
    - Quantum Optimal Control: 'examples/optimal_control.md'
    - Introspection Utilities: 'examples/introspection.md'
  - API:
    - Hilbert Spaces:
      - Base: 'api/hilbert_spaces/base.md'
      - Finite Difference: 'api/hilbert_spaces/finite_difference.md'
      - Pseudospectral: 'api/hilbert_spaces/pseudospectral.md'
      #- Spherical: 'api/hilbert_spaces/spherical.md'
      - Qubits: 'api/hilbert_spaces/qubits.md'
      - N-Level: 'api/hilbert_spaces/nlevel.md'
    - Operators: 
      - Operator: 'api/operators/operator.md'
      - Timevarying Operator: 'api/operators/timevarying.md'
      - Controlled Operator: 'api/operators/controlled.md'
    - Exponentiators:
      #- Base: 'api/exponentiators/base.md'
      - Euler: 'api/exponentiators/euler.md'
      - Split: 'api/exponentiators/split.md'
      - Composed: 'api/exponentiators/composed.md'
      - Krylov: 'api/exponentiators/krylov.md'
      - Chebyshev: 'api/exponentiators/chebyshev.md'
      - Truncated Taylor: 'api/exponentiators/truncated_taylor.md'
    - Tensor Product: 'api/tensor_product.md'
    - Controls: 'api/controls.md'
    - Timesteppers: 'api/timesteppers.md'
    - Adjoints: 'api/adjoints.md'
    - Propagators: 'api/propagator.md'
