[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "pymdown-extensions",
]
tests = [
    "pytest",
]
utils = [
    "mpmath",
]
dev = [
    "qmax[docs,tests,utils]",
    "ruff",
    "pyright",
]

[project]
authors = [
    {name = "Ahmed Allibhoy"}
]
name = "qmax"
readme = "README.md"
requires-python = ">=3.14"
version = "0.01"
dependencies = [
    "jax",
    "jaxtyping",
    "equinox",
    "lineax",
    "numpy",
    "matplotlib",
    "tqdm",
]

[tool.ruff]
# The minimum Python version that should be supported
target-version = "py314"
extend-exclude = ["*.ipynb"]
line-length = 100

[tool.ruff.lint]
fixable = ["I001", "F401", "F541"]
ignore = ["E402", "E731", "B008"]
select = ["E", "F", "I"]

[tool.pyright]
include = ["qmax"]
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false # Incompatible with eqx.AbstractVar
#reportUnnecessaryTypeIgnoreComment = true